import assert from "node:assert/strict";
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??"playwright");
const browser=await chromium.launch({headless:true});
try{
  const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];
  page.on("pageerror",error=>errors.push(error.message));
  await page.goto("http://localhost:3000");
  await page.getByRole("button",{name:"新建项目",exact:true}).first().click();
  await page.locator(".project-template-picker button").filter({hasText:"人物姿态"}).click();
  await page.locator(".intro-loader").waitFor({state:"hidden",timeout:60000});
  await page.locator(".action-library-tabs").getByRole("tab",{name:"动态",exact:true}).click();
  await page.locator(".action-card-main").filter({hasText:"转头看身后"}).click();
  await page.locator(".action-preview-controls").waitFor();
  await page.waitForTimeout(600);
  await page.locator(".action-transport button").click();
  assert.equal(await page.locator(".timeline-clip").count(),0);
  await page.screenshot({path:"/private/tmp/poseboard-action-preview.png"});
  await page.getByRole("button",{name:"保存当前姿态",exact:true}).click();
  await page.getByRole("button",{name:"取消预览",exact:true}).click();
  assert.equal(await page.locator(".action-preview-controls").count(),0);
  await page.locator(".action-card-main").filter({hasText:"举手示意"}).click();
  await page.getByRole("button",{name:"新建动作镜头",exact:true}).click();
  await page.waitForTimeout(900);
  await page.getByRole("button",{name:"项目首页",exact:true}).click();
  await page.locator(".project-home").waitFor();
  const records=await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open("poseboard-projects",1);r.onsuccess=()=>{const q=r.result.transaction("projects").objectStore("projects").getAll();q.onsuccess=()=>resolve(q.result);q.onerror=reject;};r.onerror=reject;}));
  const data=JSON.parse(Object.values(records[0].contents)[0].local["poseboard.project.v3"]);
  const saved=JSON.parse(Object.values(records[0].contents)[0].local["poseboard.savedPoses.v1"]);
  assert.ok(saved[0].rigPose && Object.keys(saved[0].rigPose.bones).length>20,"paused frame keeps actual bone data");
  assert.equal(data.videoTimeline.shots.length,1);
  assert.equal(data.animationTimeline.shots[0].actionId,"action-raise-hand");
  assert.ok(data.animationTimeline.shots[0].tracks.some(t=>t.targetId===data.currentScene.selectedModelId));
  await page.locator(".project-card-open").first().click();
  await page.locator(".intro-loader").waitFor({state:"hidden",timeout:60000});
  await page.reload();
  await page.locator(".intro-loader").waitFor({state:"hidden",timeout:60000});
  await page.screenshot({path:"/private/tmp/poseboard-action-restored.png"});
  assert.deepEqual(errors,[]);
  console.log("PASS isolated preview/cancel, create clip, actor binding, auto-save, home and reload",data.animationTimeline.shots[0].tracks.map(t=>[t.kind,t.keyframes.length]));
}finally{await browser.close();}
