import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??"playwright");
const browser=await chromium.launch({headless:true});
try{
  const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];
  page.on("pageerror",error=>errors.push(error.message));
  const ready=async()=>{await page.locator(".project-editor .editor-app").waitFor({timeout:60000});await page.locator(".intro-loader").waitFor({state:"hidden",timeout:60000});await page.locator(".model-loader").waitFor({state:"hidden",timeout:60000});};
  const home=async()=>{await page.getByRole("button",{name:"项目首页",exact:true}).click();await page.locator(".project-home").waitFor();};
  const records=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open("poseboard-projects",1);r.onsuccess=()=>{const q=r.result.transaction("projects").objectStore("projects").getAll();q.onsuccess=()=>resolve(q.result);q.onerror=reject;};r.onerror=reject;}));
  const state=p=>JSON.parse(Object.values(p.contents)[0].local["poseboard.project.v3"]);
  const open=async(project)=>{await page.goto(`http://localhost:3000/#project=${project.id}&page=${project.lastPageId}`);await page.reload();await ready();};
  const tab=name=>page.locator(".action-library-tabs").getByRole("tab",{name,exact:true}).click();
  const preview=async(name)=>{await page.locator(".action-card-main").filter({has:page.getByText(name,{exact:true})}).click();try{await page.locator(".action-preview-controls").waitFor({timeout:10000});}catch(error){await page.screenshot({path:"/private/tmp/poseboard-interaction-error.png"});console.log(await page.locator("body").innerText());throw error;}};
  const create=async()=>{await page.getByRole("button",{name:"新建项目",exact:true}).first().click();await page.locator(".project-template-picker button").filter({hasText:"人物姿态"}).click();await ready();};
  await page.goto("http://localhost:3000");await create();await home();
  const project=(await records())[0],before=state(project);
  await open(project);await tab("双人互动");await preview("拥抱");
  await page.getByRole("button",{name:"取消预览",exact:true}).click();await home();
  let after=state((await records()).find(p=>p.id===project.id));
  assert.deepEqual(after.currentScene.models.map(m=>m.id),before.currentScene.models.map(m=>m.id));
  assert.equal(after.videoTimeline.shots.length,0,"cancel does not append shots");
  await open(project);await tab("双人互动");await preview("拥抱");
  await page.locator(".action-transport input").fill("2.75");
  const [download]=await Promise.all([page.waitForEvent("download"),page.getByRole("button",{name:"保存镜头图片",exact:true}).click()]);
  const png=await readFile(await download.path());
  assert.equal(png.subarray(1,4).toString(),"PNG");
  assert.equal(png.readUInt32BE(16),1080);assert.equal(png.readUInt32BE(20),1920);
  await page.screenshot({path:"/private/tmp/poseboard-interaction-preview.png"});
  await page.getByRole("button",{name:"新建动作镜头",exact:true}).click();await home();
  after=state((await records()).find(p=>p.id===project.id));
  assert.equal(after.currentScene.models.length,2);
  assert.equal(after.animationTimeline.shots[0].tracks.filter(t=>t.kind==="pose").length,2);
  const originalShot=structuredClone(after.videoTimeline.shots[0]),originalClip=structuredClone(after.animationTimeline.shots[0]);
  await open(project);await tab("动态");await preview("坐下");
  await page.getByRole("combobox",{name:"画板比例",exact:true}).selectOption("16:9");
  await page.getByRole("button",{name:"取消预览",exact:true}).click();await home();
  const cancelled=state((await records()).find(p=>p.id===project.id));
  assert.deepEqual(Object.keys(cancelled.videoTimeline.shots[0].aspectOverrides),Object.keys(originalShot.aspectOverrides),"preview ratio does not create an original shot override");
  await open(project);await tab("动态");await preview("坐下");
  await page.getByRole("button",{name:"当前镜头另存新版本",exact:true}).click();await home();
  after=state((await records()).find(p=>p.id===project.id));
  assert.equal(after.videoTimeline.shots.length,2);
  for(const key of ["id","title","start","end","duration","color","thumbnail"])assert.deepEqual(after.videoTimeline.shots[0][key],originalShot[key],`source shot ${key} remains intact`);
  assert.deepEqual({...after.videoTimeline.shots[0].sceneSnapshot,capturedAt:0},{...originalShot.sceneSnapshot,capturedAt:0},"source scene content remains intact across auto-save captures");
  assert.deepEqual(after.animationTimeline.shots[0].tracks.filter(t=>t.keyframes.length),originalClip.tracks.filter(t=>t.keyframes.length),"source pair animation remains intact");
  assert.equal(after.currentScene.models.length,2,"existing actor slots are reused");
  assert.ok(after.videoTimeline.shots[1].sceneSnapshot.actionProps.some(prop=>prop.kind==="chair"));
  assert.deepEqual(after.videoTimeline.shots[1].sceneSnapshot.camera,originalShot.sceneSnapshot.camera,"current camera is preserved");
  assert.equal(after.videoTimeline.shots[1].duration,originalShot.duration,"a new version preserves a longer shot duration");
  await create();await home();const second=(await records()).find(p=>p.id!==project.id);
  assert.equal(state(second).videoTimeline.shots.length,0,"another project has no copied clips");
  assert.equal(state(second).currentScene.models.length,1,"another project has no copied partner");
  await open(project);await page.reload();await ready();await home();
  const restored=state((await records()).find(p=>p.id===project.id));
  assert.deepEqual(restored.animationTimeline.shots,after.animationTimeline.shots);
  assert.deepEqual(errors,[]);
  console.log("PASS pair preview cancellation, existing actor reuse, chair, camera/duration preservation, independent projects and reload");
}finally{await browser.close();}
