const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? "playwright");
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});
const page = await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
const all=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('poseboard-projects',1);r.onsuccess=()=>{const q=r.result.transaction('projects').objectStore('projects').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=reject;};r.onerror=reject;}));
const ready=async()=>{await page.locator('.project-editor .editor-app').waitFor({timeout:60000});await page.locator('.intro-loader').waitFor({state:'hidden',timeout:60000});await page.waitForTimeout(1000);};
const home=async()=>{await page.getByRole('button',{name:'项目首页',exact:true}).click();await page.locator('.project-home').waitFor();await page.waitForFunction(()=>![...document.querySelectorAll('.project-home button')].some(b=>b.textContent==='新建项目'&&b.disabled));await page.waitForTimeout(200);};
await page.goto('http://localhost:3000/');
await page.getByRole('button',{name:'新建项目',exact:true}).first().click();
await page.locator('.project-template-picker button').filter({hasText:'剧情分镜'}).click(); await ready();
assert.equal(await page.locator('.project-page-item').count(),3);
await page.locator('.recipe-card img').first().waitFor({timeout:60000});
await page.getByRole('tab',{name:'套组',exact:true}).click();await page.locator('.recipe-suite').nth(1).click();await page.getByRole('button',{name:'使用这 4 镜',exact:true}).click();
await page.locator('.project-page-item .page-open').nth(2).click(); await ready();
assert.equal(await page.locator('.timeline-clip').count(),4);
await home(); console.log('story saved');
let projects=await all();assert.equal(projects.length,1);const original=projects[0],raw=Object.values(original.contents)[0].local['poseboard.project.v3'];assert.equal(JSON.parse(raw).videoTimeline.shots.length,4);assert.equal(new Set(original.pages.map(p=>p.contentId)).size,1);
await page.getByRole('button',{name:'新建项目',exact:true}).first().click();await page.locator('.project-template-picker button').filter({hasText:'人物姿态'}).click();await ready();
assert.equal(await page.locator('.video-timeline-panel').count(),0);
await home();projects=await all();console.log('projects',projects.map(p=>[p.name,p.pages.length,p.openedAt]));assert.equal(projects.length,2);assert.equal(Object.values(projects.find(p=>p.id===original.id).contents)[0].local['poseboard.project.v3'],raw);
await page.getByRole('button',{name:'继续编辑',exact:true}).click();await ready();console.log('continuing',await page.locator('.project-workspace-header strong').innerText());
await page.locator('.page-content-reference button').filter({hasText:'复制为新方案'}).click();await page.waitForFunction(()=>document.querySelector('.project-workspace-header>span')?.textContent.includes('新方案'));await ready();
assert.equal(await page.locator('.project-page-item').count(),2);
await home();projects=await all();const pose=projects.find(p=>p.id!==original.id);console.log('copy',projects.map(p=>[p.name,p.pages.map(v=>v.contentId)]));assert.equal(new Set(pose.pages.map(p=>p.contentId)).size,2);
await page.screenshot({path:'/private/tmp/poseboard-project-home.png'});
await page.getByRole('button',{name:'继续编辑',exact:true}).click();await ready();await page.reload();await ready();assert.equal(await page.locator('.project-page-item').count(),2);
await page.screenshot({path:'/private/tmp/poseboard-project-editor.png'});
await home();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/poseboard-project-mobile.png'});
console.log('PASS templates, shared shots, immediate page flush, cross-project isolation, independent page copy, reload and pause. Errors:',JSON.stringify(errors));
assert.deepEqual(errors,[]);await browser.close();
