"use client";
/* eslint-disable @next/next/no-img-element */
import { useState } from "react";
import { shotRecipes, shotSuites, type RecipePlan, type RecipeRatio } from "./shot-recipes";
export function RecipeLibrary(p: { ratio: RecipeRatio; thumbnails: Record<string, string>; plan: RecipePlan | null; selectedIndex: number; ready: boolean; onRecipe: (id: string) => void; onSuite: (id: string) => void; onPrompt: (prompt: string) => void; onSelectIndex: (index: number) => void }) {
  const [category, setCategory] = useState("全部"); const [prompt, setPrompt] = useState(""); const [tab, setTab] = useState("镜头");
  return <aside className="recipe-library" aria-label="完整镜头预设">
    <header><h1>选一个镜头</h1><span>布置好，直接用</span></header>
    <form onSubmit={(e) => { e.preventDefault(); if (prompt.trim()) p.onPrompt(prompt.trim()); }}><label htmlFor="recipe-prompt">也可以描述你要的分镜</label><textarea id="recipe-prompt" value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="两个人对话，先交代位置，再拍反应，最后眼神特写，总共 8 秒" rows={3} /><button disabled={!prompt.trim() || !p.ready}>推荐一套</button></form>
    <div className="recipe-library-tabs" role="tablist" aria-label="预设类型">{["镜头", "套组"].map((name) => <button key={name} role="tab" aria-selected={tab === name} onClick={() => setTab(name)}>{name}</button>)}</div>
    {tab === "镜头" && <div className="recipe-categories">{["全部", "单人", "双人", "动作反应"].map((name) => <button key={name} aria-pressed={category === name} onClick={() => setCategory(name)}>{name}</button>)}</div>}
    <div className="recipe-card-list">
      {tab === "镜头" ? shotRecipes.filter((r) => category === "全部" || r.category === category).map((r) => <button className="recipe-card" key={r.id} aria-pressed={p.plan?.items[p.selectedIndex]?.recipeId === r.id} disabled={!p.ready} onClick={() => p.onRecipe(r.id)}>
        <div className={`recipe-cover ${p.ratio === "9:16" ? "portrait" : "landscape"}`}>{p.thumbnails[`${r.id}:${p.ratio}`] ? <img src={p.thumbnails[`${r.id}:${p.ratio}`]} alt={`${r.name}的${p.ratio}实际构图`} /> : <span>正在渲染镜头…</span>}</div><strong>{p.ratio === "9:16" ? "竖版" : "横版"} · {r.name}</strong><small>静态 · 默认 {r.duration} 秒</small></button>) : shotSuites.map((suite) => <button className="recipe-suite" key={suite.id} disabled={!p.ready} onClick={() => p.onSuite(suite.id)}><div className="recipe-suite-strip">{suite.recipeIds.slice(0, 3).map((id, i) => <div key={`${id}-${i}`}>{p.thumbnails[`${id}:${p.ratio}`] && <img src={p.thumbnails[`${id}:${p.ratio}`]} alt={`第 ${i + 1} 镜实际构图`} />}</div>)}</div><strong>{suite.name}</strong><span>{suite.description}</span><small>{suite.recipeIds.length} 镜 · 静态切镜预览</small></button>)}
    </div>
    {p.plan && <div className="recipe-plan"><strong>{p.plan.name} · {p.plan.items.reduce((n, i) => n + i.duration, 0).toFixed(2)} 秒</strong><div>{p.plan.items.map((item, index) => <button key={index} aria-pressed={index === p.selectedIndex} onClick={() => p.onSelectIndex(index)}>{index + 1}</button>)}</div>{p.plan.warnings.map((w, i) => <p role="status" key={i}>{w}</p>)}</div>}
  </aside>;
}
export function ShotCardView({ shots, activeId, onSelect, onReorder, onTimeline }: { shots: { id: string; index: number; thumbnail: string; title: string; promptText: string; duration: number; needsReview?: boolean }[]; activeId: string | null; onSelect: (id: string) => void; onReorder: (from: string, to: string) => void; onTimeline: () => void }) {
  const [dragging, setDragging] = useState<string | null>(null);
  return <section className="shot-card-view" aria-label="分镜卡片视图"><header><strong>分镜卡片</strong><span>拖动卡片调整顺序</span><button onClick={onTimeline}>时间轴视图</button></header><div className="shot-card-sequence">{shots.length ? shots.map((shot, index) => <article key={shot.id} draggable onDragStart={(e) => { setDragging(shot.id); e.dataTransfer.setData("text/plain", shot.id); }} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); if (dragging) onReorder(dragging, shot.id); setDragging(null); }} onDragEnd={() => setDragging(null)} className={activeId === shot.id ? "selected" : ""}><button onClick={() => onSelect(shot.id)}>{shot.thumbnail ? <img src={shot.thumbnail} alt={`镜头 ${index + 1} 预览`} /> : <div className="shot-card-empty">选择镜头以预览</div>}<strong>{String(index + 1).padStart(2, "0")} · {shot.title}</strong><small>{shot.duration.toFixed(2)} 秒{shot.needsReview ? " · 待重新确认" : ""}</small><p>{shot.promptText.slice(0, 64)}</p></button><div className="shot-card-reorder"><button disabled={!index} onClick={() => onReorder(shot.id, shots[index - 1].id)}>前移</button><button disabled={index === shots.length - 1} onClick={() => onReorder(shots[index + 1].id, shot.id)}>后移</button></div></article>) : <p>使用一个镜头或套组后，分镜卡片会自动出现在这里。</p>}</div></section>;
}
